# Generated by Django 5.0 on 2023-12-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('about_game', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/')),
            ],
        ),
    ]
